server:
  port: 8000
management:
  server:
    port: 8001
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  application:
    name: helloaxis
  profiles:
    active: sit
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    bus:
      enabled: true
    refresh:
      enabled: true
  kafka:
    bootstrap-servers: http://localhost:9093